const CREATE_PATIENT_RECORD =  'CREATE_PATIENT_RECORD'
const READ_PATIENT_RECORD = 'READ_PATIENT_RECORD'
const DELETE_PATIENT_RECORD = 'DELETE_PATIENT_RECORD'
const EDIT_PATIENT_RECORD = 'EDIT_PATIENT_RECORD'

export { CREATE_PATIENT_RECORD, READ_PATIENT_RECORD, DELETE_PATIENT_RECORD, EDIT_PATIENT_RECORD }